apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  labels:
    app: learn-voyage-chat-service
data:
  PORT: "4001"
  EMAIL: "learnvoyage2024@gmail.com"
  RMQ_URL: "amqps://rqbtlbqf:NbpGEmWqNbx5a-0XmYKweX-4TXwaum-v@puffin.rmq2.cloudamqp.com/rqbtlbqf"
  PASS: "ijwf xuuo mdbz aufu"
  STRIPE_SK: "sk_test_51PZ3biC85Qvu21M2GRfQhMiUH0wxV5a4YMa8BK6WVv6sJqGTHZBqu8vtVybWIDJp7Weur34mIKCtrYT5cUjkC7aB00kUBxh0k9"
  FRONTEND_URL: "http://localhost:5173"
  BACKEND_URL: "http://localhost:3005"
  MONGODB_URI: "mongodb+srv://learnvoyage:learnvoyage123@learnvoyage.a3qrwmv.mongodb.net/chat-service?retryWrites=true&w=majority&appName=LearnVoyage"
  ACCESS_TOKEN_PRIVATE_KEY: "LearnVoyageAccessToken"
  REFRESH_TOKEN_PRIVATE_KEY: "LearnVoyageRefreshToken"
