apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  labels:
    app: learn-voyage-notification-service
data:
  PORT: "6001"
  EMAIL: "learnvoyage2024@gmail.com"
  RMQ_URL: "amqps://rqbtlbqf:NbpGEmWqNbx5a-0XmYKweX-4TXwaum-v@puffin.rmq2.cloudamqp.com/rqbtlbqf"
  PASS: "ijwf xuuo mdbz aufu"
