apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-voyage-chat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learn-voyage-chat-service
  template:
    metadata:
      labels:
        app: learn-voyage-chat-service
    spec:
      containers:
        - name: learn-voyage-chat-service
          image: jamsheerply/learnvoyage-chat:latest
          envFrom:
            - configMapRef:
                name: chat-config
---
apiVersion: v1
kind: Service
metadata:
  name: learn-voyage-chat-service
spec:
  selector:
    app: learn-voyage-chat-service
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
